FROM nginx:latest
#RUN rm rf /usr/share/nginx/html/
COPY index.html /usr/share/nginx/html/
#RUN apt install apache2
#RUN systemctl enable apache2
#RUN systemctl restart apache2
EXPOSE 9090
WORKDIR /usr/share/nginx/html
