version: '3.8'

services:
  ng1:
    image: nginx
    restart: unless-stopped
    ports:
      - "9091:80"
    volumes:
      - ./vol:/usr/share/nginx/html

  ng2:
    image: nginx
    restart: unless-stopped
    ports:
      - "8080:80"
    volumes:
      - ./vol:/usr/share/nginx/html
